# docker-compose.prod.yml
services:
  web:
    image: ${DOCKERHUB_USERNAME}/socialnite:latest
    restart: always
    env_file:
      - .config/docker.env
    volumes:
      - ./.config/default.yml:/misskey/.config/default.yml:ro
      - files:/misskey/files
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    restart: always
    image: redis:7-alpine
    volumes:
      - ./redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  db:
    restart: always
    image: postgres:15-alpine
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

volumes:
  files:
  letsencrypt:
