apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: socialnite-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: "le"
spec:
  tls:
  - hosts:
    - socialnite.nite.tec.br
  rules:
  - host: socialnite.nite.tec.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 3000
