apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: socialnite-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - socialnite.nite.tec.br
      secretName: socialnite-tls-cert
  rules:
    - host: socialnite.nite.tec.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
